### ISSUE TITLE
i woud prefer here another extension name

### ISSUE THREAD

**Issue by Lobster1956** [TYPO3-Fluid-Template-Manager/themes_bootstrap_formhandler#1]
because of we have more than one base theme!
so **themes_formhandler4bootstrap** or something else would be better...
or it has to be switchable for bootstrap, fondation, yaml, etc.
or it has to be integrated in themes_bootstrap

**Comment by tdeuling** [comment]
Hi Rene,
target is to provide a Master-Template for each Framework in theme_formhandler.
Therefore we have currently a Master-Template for Bootstrap and Founddation. These Master-Templates must contain the same named Sub-Templates.

By using the TypoScript-Constant 'themes.framework', which should be defined in your Theme, the theme_formhandler-Extension is able to load the required Template.
Take a look at https://github.com/typo3-themes/themes_formhandler/blob/master/Resources/Private/TypoScript/ContactBasic/setup.txt#L20
When you're changing the Theme in your TYPO3-Instance, and the new Theme uses another Framework, formhandler will use the same Form-Template but render it with the related Master-Template. 

It would be great when you will support us by creating a Master-Template for YAML.
We could discuss it by phone if you want.

Have a nice weekend,
Thomas
